# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: my-docker-id  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: python_flask_ado  # Replace with the name of the image you want to publish

steps:

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: bplab-azure-container-reg

#- script: docker build -t $(imageName) . 
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    containerRegistry: bplab-azure-container-reg
    repository: azure_devops_python_flask
    tags: 0.1

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

